Shutdown server gracefully
docsocsf/sponsor-portal-OLD pull request #15
Opened 2017-08-07 11:56 UTC by egnwd

2017-09-24 13:02 UTC, levex submitted a review, later dismissed
LGTM.

2017-09-24 20:25 UTC, mauriceyap submitted a review, later dismissed

2017-09-25 06:57 UTC, plietar requested changes

2017-09-25 06:57 UTC, plietar commented on Makefile
> -	go run web/*.go
Success is normally exit code 0, not 1.
Also you should add `exit $$exit` inside the `if` to make sure make errors as well

2017-10-01 16:07 UTC, plietar approved these changes

2017-10-01 16:07 UTC, merged