Basic Auth
docsocsf/sponsor-portal-OLD pull request #28
Opened 2017-10-01 16:51 UTC by jamesprinc3

2017-10-01 17:10 UTC, egnwd requested changes

2017-10-01 17:10 UTC, egnwd commented on auth/basicAuth.go
> +		Email: user + "ic.ac.uk",
Does this need an `"@"`? Also this can be a const

2017-10-01 17:10 UTC, egnwd commented on auth/ldap.go
> +	tlsConfig := &tls.Config{ServerName: "ldaps-vip.cc.ic.ac.uk"}
`"ldaps-vip.cc.ic.ac.uk"` can be a const

2017-10-01 17:10 UTC, egnwd commented on auth/ldap.go
> +		"dc=ic,dc=ac,dc=uk", // The base dn to search
Looks like a const

2017-10-01 17:10 UTC, egnwd commented on auth/ldap.go
> +		[]string{"dn", "cn", "givenName", "sn"},                    // A list attributes to retrieve
Should this be a const too?

2017-10-01 17:10 UTC, egnwd commented on auth/ldap.go
> +	return contains(entries[0].GetAttributeValues("memberOf"), "CN=zz-icu-docsoc-members-dl,OU=Distribution,OU=Groups,OU=Imperial College (London),DC=ic,DC=ac,DC=uk")
const too

2017-10-01 17:10 UTC, egnwd commented on auth/ldap.go
> +	surname := entries[0].GetAttributeValue("sn")
we could have a block of keys?

2017-10-01 17:10 UTC, egnwd commented on auth/ldap.go
> +	err = l.Bind(username + "@IC.AC.UK", password)
Does this need to be all caps? if not then can we unify it with the other domain const.

2017-10-01 17:10 UTC, egnwd commented on auth/ldap.go
> +	log.Println(meh)
Remove this

2017-10-01 17:10 UTC, egnwd commented on seed/users.csv
> +James Prince,jeprogramming@gmail.com
We can remove this file now, and the seeding from the Makefile

2017-10-01 17:38 UTC, plietar commented on auth/basicAuth.go
> +package auth
File names are generally snake_case in Go

2017-10-01 17:38 UTC, plietar commented on auth/ldap.go
> +		log.Fatal(err)
This would crash the server if an incorrect username is used

2017-10-01 17:38 UTC, plietar commented on .env
> +AUTH_COOKIE_SECRET=topsecret
Keep this close to `AUTH_BASE_URL`

2017-10-01 17:38 UTC, plietar commented on auth/ldap.go
> +func contains(slice []string, item string) bool {
Why make the map at all ? Just iterate and stop when you found the one you want.

This is only useful is you're going to lookup many keys, which is not the case here

2017-10-01 17:38 UTC, plietar commented on auth/ldap.go
> +	// TLS, for testing purposes disable certificate verification, check https://golang.org/pkg/crypto/tls/#Config for further information.
That comment should be removed I think

2017-10-01 17:38 UTC, plietar commented on auth/ldap.go
> +	searchResult := search(l, username)
This is going to make two search requests, once for isDoCSoc and once on this line.

You can just use the `searchResult` to determine if the member is in DoCSoc.

2017-10-01 17:38 UTC, plietar commented on auth/ldap.go
> +		log.Println("User is not a member of DoCSoc")
Do we want to error here ?

2017-10-02 10:55 UTC, jamesprinc3 commented on auth/ldap.go
> +	err = l.Bind(username + "@IC.AC.UK", password)
which other domain const? Is this in a different file somewhere?

2017-10-02 10:59 UTC, egnwd commented on auth/ldap.go
> +	err = l.Bind(username + "@IC.AC.UK", password)
https://github.com/docsocsf/sponsor-portal/pull/28/files#diff-e456e9043e876b919fd7064bdec373ceR62

2017-10-02 11:00 UTC, egnwd commented on auth/ldap.go
> +		fmt.Println(err)
use `log` instead of `fmt`

2017-10-02 11:19 UTC, jamesprinc3 commented on auth/ldap.go
> +	err = l.Bind(username + "@IC.AC.UK", password)
sorry yes my bad

2017-10-02 12:09 UTC, egnwd submitted a review, later dismissed

2017-10-02 12:09 UTC, egnwd commented on auth/basic_auth.go
> +		log.Println(err)
Won't this always be `nil`?

2017-10-02 12:09 UTC, egnwd commented on auth/basic_auth.go
> +		log.Println(err.Error())
`log.Println(err)` should be fine

2017-10-02 12:09 UTC, egnwd commented on auth/ldap.go
> +	spew.Dump(entries)
We probs don't want this

2017-10-02 12:09 UTC, egnwd commented on auth/ldap.go
> +	//// Rebind as the service user for any further queries
Can this just be removed?

2017-10-02 12:09 UTC, egnwd commented on model/user.go
>  			log.Printf("%#v\n", u)
Don't need this log anymore

2017-10-02 12:42 UTC, plietar commented on Makefile
>  USER_CMD := "${SEED_CMD} -c \"COPY users (name, email) FROM STDIN WITH CSV\""
this can go away as well

2017-10-02 12:43 UTC, plietar commented on auth/ldap.go
> +	size int
the size never gets reused, so there's no need to store it

2017-10-02 12:44 UTC, plietar commented on auth/ldap.go
> +	conn chan interface{}
This doesn't have to be an `interface {}`, we always use it with `ldap.Conn`

2017-10-02 12:45 UTC, plietar commented on auth/ldap.go
> +	if err != nil {
This condition is not necessary. You can just use `return l, err`, whether or not `err` is null

2017-10-02 12:45 UTC, plietar commented on auth/ldap.go
> +func ldapsConnection() (interface{}, error) {
Should rename that to something like `createLdapsConnection`

2017-10-02 12:46 UTC, plietar commented on auth/ldap.go
> +func ldapsConnection() (interface{}, error) {
Or `make` or whatever

2017-10-02 12:47 UTC, plietar commented on auth/ldap.go
> +	if ok, _ := wrapper.isDoCSoc(username); !ok {
This should come after the check of whether the user even exists, otherwise non existent users will get this error message.

2017-10-02 12:47 UTC, plietar commented on auth/password_auth.go
> +		Name: "Not Joe Bloggs",
Doesn't have to be implemented in this PR, but at least put a TODO or FIXME

2017-10-02 12:54 UTC, egnwd commented on auth/password_auth.go
> +		Name: "Not Joe Bloggs",
Don't think this is even needed?

2017-10-02 18:16 UTC, plietar commented on auth/ldap.go
>  	pool.ReleaseConnection(l)
Even though it doesn't really matter, it would be good to unbind before returning to the pool.

2017-10-02 18:16 UTC, plietar commented on auth/ldap.go
>  type ConnectionPoolWrapper struct {
This could simply be called `ConnectionPool`, it doesn't really wrap anything

2017-10-02 18:16 UTC, plietar commented on auth/auth.go
> +	password string
These can be removed now that we don't bind the service account.

2017-10-02 18:16 UTC, plietar commented on auth/ldap.go
> +func init() {
Please avoid global variables and ` init` functions. It will make testing and re-usability harder.
Put a field in ` LDAPWrapper` (there's already one that is unused ?) and make a create function

2017-10-02 18:16 UTC, plietar commented on auth/ldap.go
> +type InitFunction func() (*ldap.Conn, error)
Move this just before the `InitPool`.

2017-10-02 18:16 UTC, plietar commented on auth/ldap.go
> +func (wrapper *LDAPWrapper) search(accountName string) ([]*ldap.Entry, error) {
This isn't used anymore it seems

2017-10-19 16:26 UTC, plietar submitted a review, later dismissed

2017-10-21 23:39 UTC, plietar approved these changes

2017-10-21 23:39 UTC, merged